//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonsv
    {
        public string mahd { get; set; }
        public string masv { get; set; }
        public Nullable<int> tienphong { get; set; }
        public Nullable<int> tienkhac { get; set; }
        public Nullable<int> tongtien { get; set; }
    }
}
