//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonphong
    {
        public string mahd { get; set; }
        public string maphong { get; set; }
        public Nullable<int> tiendien { get; set; }
        public Nullable<int> tiennuoc { get; set; }
        public Nullable<int> tienvs { get; set; }
        public Nullable<int> tongtien { get; set; }
    
        public virtual Phongkt Phongkt { get; set; }
    }
}
