//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewdanhsachsvvao
    {
        public string masv { get; set; }
        public string malop { get; set; }
        public string maphong { get; set; }
        public string hoten { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
    }
}
