//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOKTX
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewdanhsachphong
    {
        public string maphong { get; set; }
        public string tenday { get; set; }
        public string vitri { get; set; }
        public string loaiphong { get; set; }
        public string tinhtrang { get; set; }
    }
}
